//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.544
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oiko.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;AttachDbFilename=\"C:\\Users\\Djonathas\\Google Drive\\Documentos\\4º Per" +
            "íodo\\4N - LPC I\\G2\\Projeto OIKO\\Banco de Dados\\OikoDataBase.mdf\";Persist Securit" +
            "y Info=True;User ID=sa;Password=123;Connect Timeout=30;User Instance=False")]
        public string OikoDataBaseConnectionString {
            get {
                return ((string)(this["OikoDataBaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;AttachDbFilename=|DataDirectory|\\OikoDataBase.mdf;User ID=sa;Passwo" +
            "rd=123;User Instance=False")]
        public string OikoDataBaseConnectionString1 {
            get {
                return ((string)(this["OikoDataBaseConnectionString1"]));
            }
        }
    }
}
